In [1]:
import numpy as np

In [2]:
arr = np.array([5, 10, 15, 20, 25])
print(arr)

[ 5 10 15 20 25]


In [3]:
type(arr)

numpy.ndarray

In [4]:
# accessing the array element using index
arr[2] # here 2 means 3rd element

15

In [5]:
# doing arithmetic operations
arr[2]+arr[4]

40

In [6]:
arr[1] * arr[3]

200

In [7]:
# slicing in the array using [:]

print(np.add(5, arr[:]))

[10 15 20 25 30]


In [12]:
print(np.subtract(arr[:], 5))
print(arr)

[ 0  5 10 15 20]
[ 5 10 15 20 25]


In [13]:
print(arr.dtype)

int64


In [16]:
stringArr = np.array(['sanoj', 'aies', 'lab','hai' ])
print(stringArr.dtype)

<U5


In [17]:
boolArr = np.array([True, False, True, False])
print(boolArr.dtype)

bool


In [19]:
a = np.array([1,2,3,4,3,4,5,6,5,6,7,8])
# np.unique gets all the unique element

c = np.unique(a)
print(c)

[1 2 3 4 5 6 7 8]


In [20]:
 x = arr.copy() # it means x copies all the elemnent of the arr array

In [21]:
print(x)

[ 5 10 15 20 25]


In [22]:
x[0] = 100
x[4] = 150
print(x)

[100  10  15  20 150]


In [23]:
print(arr)

[ 5 10 15 20 25]


In [25]:
newArr = np.array([[1,2,3,4,5], [5,10,15,20,25]])
print(newArr)

[[ 1  2  3  4  5]
 [ 5 10 15 20 25]]


In [26]:
print(newArr.shape)

(2, 5)


In [27]:
newArr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  5],
       [10, 15],
       [20, 25]])

In [28]:
# to traverse in array 
for x in arr:
    print(x)

5
10
15
20
25


In [36]:
# concatenation in array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9,10])

newarr = np.concatenate((a,b))
print(newarr)

[ 1  2  3  4  5  5  6  7  8  9 10]


In [41]:
arr1 = np.array_split(newarr, 4)
print(arr1)

[array([1, 2, 3]), array([4, 5, 5]), array([6, 7, 8]), array([ 9, 10])]


In [43]:
x = np.where(newarr == 5)
print(x)

(array([4, 5]),)


In [45]:
newarr = np.array([1,2,-1,0, 10,15, 2, 4, 5])

print(np.sort(newarr))

[-1  0  1  2  2  4  5 10 15]


In [48]:
arr = np.array([1,2,3,4,5])
x = [True, False, True, False, False]
newarr = arr[x]
print(newarr)

[1 3]
